/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignRouteImport } from './routes/sign'
import { Route as PackagePreviewRouteImport } from './routes/package-preview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLogisticsRouteImport } from './routes/admin.logistics'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminKidsClubRouteImport } from './routes/admin.kids-club'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminClearanceRouteImport } from './routes/admin.clearance'
import { Route as AdminCallLogsRouteImport } from './routes/admin.call-logs'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAccountRouteImport } from './routes/admin.account'

const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagePreviewRoute = PackagePreviewRouteImport.update({
  id: '/package-preview',
  path: '/package-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticsRoute = AdminLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKidsClubRoute = AdminKidsClubRouteImport.update({
  id: '/kids-club',
  path: '/kids-club',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClearanceRoute = AdminClearanceRouteImport.update({
  id: '/clearance',
  path: '/clearance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallLogsRoute = AdminCallLogsRouteImport.update({
  id: '/call-logs',
  path: '/call-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/package-preview': typeof PackagePreviewRoute
  '/sign': typeof SignRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/call-logs': typeof AdminCallLogsRoute
  '/admin/clearance': typeof AdminClearanceRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/kids-club': typeof AdminKidsClubRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/package-preview': typeof PackagePreviewRoute
  '/sign': typeof SignRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/call-logs': typeof AdminCallLogsRoute
  '/admin/clearance': typeof AdminClearanceRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/kids-club': typeof AdminKidsClubRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/package-preview': typeof PackagePreviewRoute
  '/sign': typeof SignRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/call-logs': typeof AdminCallLogsRoute
  '/admin/clearance': typeof AdminClearanceRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/kids-club': typeof AdminKidsClubRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/feedback'
    | '/login'
    | '/package-preview'
    | '/sign'
    | '/admin/account'
    | '/admin/bookings'
    | '/admin/call-logs'
    | '/admin/clearance'
    | '/admin/contracts'
    | '/admin/feedback'
    | '/admin/kids-club'
    | '/admin/leads'
    | '/admin/logistics'
    | '/admin/payments'
    | '/admin/promotions'
    | '/admin/tournaments'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feedback'
    | '/login'
    | '/package-preview'
    | '/sign'
    | '/admin/account'
    | '/admin/bookings'
    | '/admin/call-logs'
    | '/admin/clearance'
    | '/admin/contracts'
    | '/admin/feedback'
    | '/admin/kids-club'
    | '/admin/leads'
    | '/admin/logistics'
    | '/admin/payments'
    | '/admin/promotions'
    | '/admin/tournaments'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/feedback'
    | '/login'
    | '/package-preview'
    | '/sign'
    | '/admin/account'
    | '/admin/bookings'
    | '/admin/call-logs'
    | '/admin/clearance'
    | '/admin/contracts'
    | '/admin/feedback'
    | '/admin/kids-club'
    | '/admin/leads'
    | '/admin/logistics'
    | '/admin/payments'
    | '/admin/promotions'
    | '/admin/tournaments'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  PackagePreviewRoute: typeof PackagePreviewRoute
  SignRoute: typeof SignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package-preview': {
      id: '/package-preview'
      path: '/package-preview'
      fullPath: '/package-preview'
      preLoaderRoute: typeof PackagePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistics': {
      id: '/admin/logistics'
      path: '/logistics'
      fullPath: '/admin/logistics'
      preLoaderRoute: typeof AdminLogisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kids-club': {
      id: '/admin/kids-club'
      path: '/kids-club'
      fullPath: '/admin/kids-club'
      preLoaderRoute: typeof AdminKidsClubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clearance': {
      id: '/admin/clearance'
      path: '/clearance'
      fullPath: '/admin/clearance'
      preLoaderRoute: typeof AdminClearanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/call-logs': {
      id: '/admin/call-logs'
      path: '/call-logs'
      fullPath: '/admin/call-logs'
      preLoaderRoute: typeof AdminCallLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCallLogsRoute: typeof AdminCallLogsRoute
  AdminClearanceRoute: typeof AdminClearanceRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminKidsClubRoute: typeof AdminKidsClubRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLogisticsRoute: typeof AdminLogisticsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCallLogsRoute: AdminCallLogsRoute,
  AdminClearanceRoute: AdminClearanceRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminKidsClubRoute: AdminKidsClubRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLogisticsRoute: AdminLogisticsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  PackagePreviewRoute: PackagePreviewRoute,
  SignRoute: SignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
